### ISSUE TITLE
Tribuo KmeansTrainer doesn't work with Java 11 (or any later version) + SecurityManager because of using ForkJoinPool

### ISSUE THREAD

**Issue by spbjss** [oracle/tribuo#158]
**Describe the bug**
From Java 11, the security policies doesn’t get propagated to ForkJoinPool worker threads if a SecurityManager is present ( https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ForkJoinPool.html )
Kmeans depends on ForkJoinPool to run the training tasks: https://github.com/oracle/tribuo/blob/v4.1.0/Clustering/KMeans/src/main/java/org/tribuo/clustering/kmeans/KMeansTrainer.java#L197 
So, any java application relay on SecurityManager and security policies won't able to work with Tribuo Kmeans because of AccessControlException.

**To Reproduce**
We have a Java application with security manager and security policy, our Java application could work with Tribuo Kmeans and Java 8. But when the Java application (with Tribuo Kmeans) work with Java 11, Java 14 or Java 15, there would be AccessControlException:
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThreadGroup")

**Expected behaviour**
The security policy defined by the Java application should be applied to any threads.

**Screenshots**
N/A.

**System information:**

 - OS: [e.g., Linux]
 - Java Version: [e.g.,  11, 14 & 15]
 - JDK Vendor: [e.g., Oracle & OpenJDK ]

**Additional context**
Reference URLs:
https://stackoverflow.com/questions/55333290/jdk11-security-policies-doesn-t-get-propagated-to-forkjoinpool-worker-threads
http://5.9.10.113/66435138/how-to-perform-the-parallel-execution-under-a-collection-when-securitymanager-is
http://mail.openjdk.java.net/pipermail/core-libs-dev/2013-December/024044.html
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ForkJoinPool.html

**Comment by Craigacp** [comment]
Is there a specific security.policy file that triggers this or is it any installation of a SecurityManager?

**Comment by Craigacp** [comment]
Also can you paste the stack trace you get? Tribuo doesn't use the default ForkJoinPool anywhere so I'm surprised we're hitting this issue.

**Comment by ylwu-amzn** [comment]
@Craigacp Thanks a lot! BTW, are you running on Java 8?

**Comment by Craigacp** [comment]
I think there are deployments on 8 and 11, and we run the CI on 8, 11 and 17. Not sure if any are using a SecurityManager though.

Did granting that privilege fix your issue?

**Comment by ylwu-amzn** [comment]
No, this is the stack trace

```
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThreadGroup")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:?]
        at java.security.AccessController.checkPermission(AccessController.java:1036) ~[?:?]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:408) ~[?:?]
        at org.opensearch.secure_sm.SecureSM.checkThreadGroupAccess(SecureSM.java:205) ~[opensearch-secure-sm-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
        at org.opensearch.secure_sm.SecureSM.checkAccess(SecureSM.java:160) ~[opensearch-secure-sm-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
        at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:311) ~[?:?]
        at java.lang.Thread.<init>(Thread.java:421) ~[?:?]
        at java.lang.Thread.<init>(Thread.java:707) ~[?:?]
        at java.lang.Thread.<init>(Thread.java:540) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.<init>(ForkJoinWorkerThread.java:100) ~[?:?]
        at java.util.concurrent.ForkJoinPool$DefaultForkJoinWorkerThreadFactory$1.run(ForkJoinPool.java:720) ~[?:?]
        at java.util.concurrent.ForkJoinPool$DefaultForkJoinWorkerThreadFactory$1.run(ForkJoinPool.java:717) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:391) ~[?:?]
        at java.util.concurrent.ForkJoinPool$DefaultForkJoinWorkerThreadFactory.newThread(ForkJoinPool.java:716) ~[?:?]
        at java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1329) ~[?:?]
        at java.util.concurrent.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1353) ~[?:?]
        at java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1478) ~[?:?]
        at java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:1912) ~[?:?]
        at java.util.concurrent.ForkJoinPool.externalSubmit(ForkJoinPool.java:1930) ~[?:?]
        at java.util.concurrent.ForkJoinPool.submit(ForkJoinPool.java:2506) ~[?:?]
```

**Comment by Craigacp** [comment]
Do you have the part of the stack trace which has a Tribuo class in it?

**Comment by Craigacp** [comment]
I looked into the `SecureSM` class a little bit, and that notes that it has tighter thread group restrictions than the default `SecurityManager` - https://github.com/elastic/securesm/blob/master/src/main/java/org/elasticsearch/SecureSM.java#L34. That's presumably why I didn't see this when I was testing before as I didn't realise ElasticSearch/OpenSearch had it's own implementation of `SecurityManager`.

Try giving the Tribuo jar `modifyThreadGroup` too:

```
grant codebase "file:/path/to/tribuo-clustering-kmeans-4.1.0.jar" {
        permission java.lang.RuntimePermission "modifyThread";
        permission java.lang.RuntimePermission "modifyThreadGroup";
};
```

**Comment by ylwu-amzn** [comment]
> Do you have the part of the stack trace which has a Tribuo class in it?

Updated the original comments, add the Tribuo class part. We are using
 `compile group: 'org.tribuo', name: 'tribuo-clustering-kmeans', version: '4.0.2'`

> Try giving the Tribuo jar modifyThreadGroup too:

I tried, not work. Like @spbjss said "the security policies doesn’t get propagated to ForkJoinPool worker threads if a SecurityManager is present"

**Comment by Craigacp** [comment]
Well, I've managed to get it to work using Tribuo 4.0.2 and the built in Java `SecurityManager`. The policy needs to be granted to all the code in the stack trace as the FJP creation isn't inside `AccessController.doPrivileged`. I successfully ran one of the unit tests using the following policy (saved as `tribuo.policy`):

```
grant codeBase "file:/path/to/tribuo/test/classes" {
        permission java.lang.RuntimePermission "modifyThread";
        permission java.lang.RuntimePermission "modifyThreadGroup";
};

grant codeBase "file:/path/to/tribuo/Clustering/KMeans/target/tribuo-clustering-kmeans-4.0.2-jar-with-dependencies.jar" {
        permission java.lang.RuntimePermission "modifyThread";
        permission java.lang.RuntimePermission "modifyThreadGroup";
        permission java.lang.RuntimePermission "accessDeclaredMembers";
        permission java.lang.reflect.ReflectPermission "suppressAccessChecks";
        permission java.util.logging.LoggingPermission "control";
        permission java.io.FilePermission "<<ALL FILES>>", "read";
        permission java.util.PropertyPermission "*", "read,write";
};
```

The extra permissions are used to allow our reflective provenance system to work, and could be minimized further depending on which file locations are used. I used the following command line: 

```
tribuo$ java -cp Clustering/KMeans/target/tribuo-clustering-kmeans-4.0.2-jar-with-dependencies.jar:. -Djava.security.manager -Djava.security.policy=tribuo.policy TestKMeans
```

Whenever I try to install SecureSM in Java 11 it causes the JVM to crash. Can you provide me a JVM startup string which successfully installs the SecureSM?

I was using the following command line:
```
tribuo$ java -cp opensearch-secure-sm-1.2.0.jar:Clustering/KMeans/target/tribuo-clustering-kmeans-4.0.2-jar-with-dependencies.jar:. -Djava.security.manager=org.opensearch.secure_sm.SecureSM -Djava.security.policy=tribuo.policy TestKMeans
```

**Comment by Craigacp** [comment]
Looks like adding `System.setSecurityManager(new org.opensearch.secure_sm.SecureSM());` to the start of my program correctly installs `SecureSM` and then I can replicate the issue. This seems to be a specific interaction between `SecureSM` and `ForkJoinPool`, which isn't present when using the default Java `SecurityManager`, so it's really a problem for the developers of SecureSM, or OpenJDK's core-libs team.

Is single threaded execution sufficient when running under `SecureSM`? We could modify `KMeansTrainer` so it doesn't use a `ForkJoinPool` for a single thread, which should allow it to run, but as I mentioned above rewriting it to use a different threading mechanism for multi-threaded execution would be a breaking change and take some time. Given `SecurityManager` is deprecated for removal in Java 17, I'm not sure rearchitecting Tribuo to allow running with a non-standard `SecurityManager` like `SecureSM` is worthwhile.

**Comment by ylwu-amzn** [comment]
Thanks @Craigacp. 
Yes, `SecureSM` has stricter check than default `SecurityManager`. Kmeans will break as we are using `SecureSM`.

I think it's reasonable to remove `ForkJoinPool` for a single thread. But we may need to look for other ML lib if single-thread Kmeans doesn't perform well. So it will be good if you can replace `ForkJoinPool` for multi-thread as well, so we can save effort to integrate another ML lib.

**Comment by Craigacp** [comment]
Ok, I've got a branch which doesn't use the FJP in single threaded computation - https://github.com/oracle/tribuo/commit/4c6247888cce36188a089d517da1f000beb11b87. Do you know if the data you are clustering is sparse or not? If it's actually dense, then there are further performance optimisations which will let Tribuo use dense vectors rather than sparse ones which we can apply. We did this for linear sgd models in 4.1, but haven't got around to applying that optimisation everywhere yet.

**Comment by ylwu-amzn** [comment]
Thanks a lot! I think that's ok to not backport to `4.0.2`, we can use `4.1.1`, or upgrade to `4.2.0` if it works.

**Comment by Craigacp** [comment]
I've updated PR #197 with the fix discussed in https://github.com/opensearch-project/OpenSearch/issues/1649.

**Comment by ylwu-amzn** [comment]
@Craigacp , thanks for adding custom thread factory. Is this still true for your release plan?
> We can probably backport the single threaded fix into 4.1.1 which will arrive around the same time 4.2.0 lands, but it's not going to be backported to 4.0.2.

**Comment by Craigacp** [comment]
Yes, that's still the plan. I also implemented the dense vector optimization for `KMeansTrainer`, but I'm undecided if that should go into `4.2.0` as it makes a backwards incompatible change to a protected method signature. I've not seen anyone subclass `KMeansTrainer`, but that doesn't mean it hasn't happened.

**Comment by ylwu-amzn** [comment]
Got it. If the BWC is a problem, how about split the PR so you can merge custom thread factory fix first? You can have some time to rethink how to support BWC and send a separate PR. One way I can think is adding a new method and deprecate current one.

**Comment by Craigacp** [comment]
Sorry, I was unclear, the performance optimization is in a separate branch. We will merge the thread factory fix first and that will definitely be in `4.2.0` and `4.1.1`.

**Comment by ylwu-amzn** [comment]
Oh, I misunderstood, thought the optimization is in the same PR. That sounds good. The performance optimization is not blocking issue for us now. Will be good if we can have that in next release 4.2.0, but respect your plan.

**Comment by Craigacp** [comment]
The fix has ben merged into `main` and we've released `v4.1.1` today. It'll take several days to get it on Maven Central, there's an internal process we need to go through as we don't have automatic deployments setup yet.

**Comment by ylwu-amzn** [comment]
@Craigacp seems v4.1.1 still not ready, I checked this https://mvnrepository.com/artifact/org.tribuo/tribuo-clustering-kmeans

**Comment by Craigacp** [comment]
Yeah, sorry it got held up a little bit by some internal process. Still working through the 4.2.0 release process as well, which should hopefully be tagged next week, though the binaries for that will take longer as everyone is on vacation between Christmas & New Year.

**Comment by ylwu-amzn** [comment]
Sure, thanks a lot. No worry, not so urgent. Happy holiday!

**Comment by Craigacp** [comment]
`4.2.0` has been tagged, and both `4.1.1` and `4.2.0` are now available in Maven Central. The search indices are slowly updating, but the jars themselves are available.
